# Generated by Django 4.2 on 2023-05-07 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('sponsor', models.CharField(max_length=20, verbose_name='主办方')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('place', models.CharField(max_length=40, verbose_name='地点')),
                ('introduction', models.CharField(max_length=100, verbose_name='简介')),
                ('tag', models.CharField(max_length=20, verbose_name='标签')),
                ('score', models.IntegerField(verbose_name='积分')),
                ('apply_num', models.IntegerField(verbose_name='允许申请人数')),
                ('applied_num', models.IntegerField(verbose_name='已申请人数')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('img_path', models.ImageField(upload_to='file/img', verbose_name='活动logo图片路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '提问',
                'verbose_name_plural': '提问',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('area', models.CharField(max_length=40, verbose_name='地区')),
                ('school', models.CharField(max_length=40, verbose_name='学校')),
                ('major', models.CharField(max_length=20, verbose_name='专业')),
                ('role', models.IntegerField(default=0, verbose_name='角色')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('introduction', models.CharField(max_length=100, verbose_name='简介')),
                ('tag', models.CharField(max_length=20, verbose_name='标签')),
                ('img_path', models.ImageField(upload_to='file/img', verbose_name='视频封面图片路径')),
                ('score', models.IntegerField(verbose_name='积分')),
                ('url', models.CharField(max_length=100, verbose_name='视频url')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='Video_study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zyz.video', verbose_name='视频id')),
            ],
            options={
                'verbose_name': '视频学习',
                'verbose_name_plural': '视频学习',
                'db_table': 'video_study',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zyz.question', verbose_name='问题id')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Activity_apply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zyz.activity', verbose_name='活动id')),
            ],
            options={
                'verbose_name': '活动申请',
                'verbose_name_plural': '活动申请',
                'db_table': 'activity_apply',
            },
        ),
    ]
