# Generated by Django 4.2 on 2023-05-13 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zyz', '0002_user_create_time_user_level_user_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_path',
            field=models.FileField(default=datetime.datetime(2023, 5, 13, 5, 44, 28, 421275, tzinfo=datetime.timezone.utc), upload_to='file/video', verbose_name='视频路径'),
            preserve_default=False,
        ),
    ]
