# Generated by Django 4.2 on 2023-05-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zyz', '0003_remove_video_url_video_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
            preserve_default=False,
        ),
    ]
