# Generated by Django 4.2 on 2023-07-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zyz', '0004_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.IntegerField(default=0, verbose_name='类型'),
            preserve_default=False,
        ),
    ]
